### PR TITLE
Add privacy pages

### PR DESCRIPTION
**Pull request by JuliaEvseeva**
This PR brings new privacy pages:
- Development Support Agreement;
- Contributor License Agreement;
- Privacy Statement

Pages are provided:
- /development-support-agreement
- /contributor-agreement
- /privacy-statement

### CODE REVIEW

**Comment by oleksandra-kovalenko** [comment]
> * /privacy/development-support-agreement
> * /privacy/contributor-agreement

@JuliaEvseeva Please place these agreements under the root directory:
/development-support-agreement
/contributor-agreement

**Comment by JuliaEvseeva** [comment]
@andreySadomovskiy, @oleksandra-kovalenko, PTAL.

**Review by andreySadomovskiy — APPROVED** [review]
@JuliaEvseeva , I don't have comments regarding the code.

**Review by oleksandra-kovalenko — APPROVED** [review]
LGTM

**Pull request merged**
