### PR TITLE
Add Resources page

### LINKED ISSUE #211: Add Resources page
Let's have it as a section under `Docs`. It would serve as supplementary learning materials. We'll be adding links to this section as long as we discover something useful for people new to DDD.

The pages would be:
  * People — Eric Evans, Greg Young, Vaughn Vernon, Alberto Brandolini (with photos, brief description of contributions, and links to GitHub or other profiles).
  * Books
  * Blogs — links to popular and useful blogs on DDD (e.g. Virtual DDD or DDD Weekly).
  * Libraries and Frameworks — why don't we link to other libraries and our competition? People would find it anyway, but listing them would answer a simple question like: “Do you know about the library/framework Xxx?”
  * Sites — community sites, sites of notable people or companies in the DDD field.

### PR DESCRIPTION
**Pull request by JuliaEvseeva**
This PR closes #211

This PR brings a new Resources section under `Docs`.
The new section consists of the following pages:
- Books;
- People;
- Blogs;
- Sites;
- Communities;
- Libraries and Frameworks.

### CODE REVIEW

**Comment by JuliaEvseeva** [comment]
@andreySadomovskiy, PTAL.

**Comment by alexander-yevsyukov** [comment]
@JuliaEvseeva, please use the Draft status for Pull Requests in progress, instead of the “WIP” suffix.

**Comment by JuliaEvseeva** [comment]
@alexander-yevsyukov, @oleksandra-kovalenko, PTAL.

**Comment by oleksandra-kovalenko** [comment]
LGTM

**Pull request merged**
